version: '3.8'
services:
  app:
    image: studentapp:latest
    ports:
      - "8084:8084"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/studentdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=studentdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
